In [23]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder #for our Label encoding
%matplotlib inline

In [24]:
df = pd.read_csv("customer_analysis_Data_Transformated.csv")

In [25]:
df

,coverage,education,location_code,policy,renew_offer_type,sales_channel,vehicle_class,vehicle_size,state_Arizona,state_California,...,policy_type_Special Auto,customer_lifetime_value,income,monthly_premium_auto,months_since_last_claim,months_since_policy_inception,number_of_open_complaints,number_of_policies,total_claim_amount,month
0,1,3.0,3,1,3,1,1,1,1,0,...,0,4809.216960,48029,61,7.000000,52,0.000000,9,292.800000,2
1,1,3.0,3,4,4,2,1,1,0,1,...,0,2228.525238,0,64,3.000000,26,0.000000,1,744.924331,1
2,1,2.0,3,4,3,2,2,1,0,0,...,0,14947.917300,22139,100,34.000000,31,0.000000,2,480.000000,2
3,2,3.0,3,1,2,3,1,1,0,0,...,0,22332.439460,49078,97,10.000000,3,0.000000,2,484.013411,1
4,3,2.0,3,5,1,3,1,1,0,0,...,0,9025.067525,23675,117,15.149071,31,0.384256,7,707.925645,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10905,3,2.0,3,6,3,4,5,1,0,0,...,0,15563.369440,0,253,15.149071,40,0.384256,7,1214.400000,1
10906,1,3.0,2,4,2,3,1,1,0,0,...,0,5259.444853,61146,65,7.000000,68,0.000000,6,273.018929,1
10907,2,2.0,1,1,1,4,6,1,1,0,...,0,23893.304100,39837,201,11.000000,63,0.000000,2,381.306996,2
10908,3,3.0,2,6,1,3,2,1,0,1,...,0,11971.977650,64195,158,0.000000,27,4.000000,6,618.288849,2
10909,1,2.0,3,6,4,4,2,1,0,1,...,0,6857.519928,0,101,31.000000,1,0.000000,3,1021.719397,1

In [26]:
df.columns

Index(['coverage', 'education', 'location_code', 'policy', 'renew_offer_type',
       'sales_channel', 'vehicle_class', 'vehicle_size', 'state_Arizona',
       'state_California', 'state_Nevada', 'state_Oregon', 'state_Washington',
       'response_No', 'response_Yes', 'employmentstatus_Disabled',
       'employmentstatus_Employed', 'employmentstatus_Medical Leave',
       'employmentstatus_Retired', 'employmentstatus_Unemployed',
       'marital_status_Divorced', 'marital_status_Married',
       'marital_status_Single', 'gender_F', 'gender_M',
       'policy_type_Corporate Auto', 'policy_type_Personal Auto',
       'policy_type_Special Auto', 'customer_lifetime_value', 'income',
       'monthly_premium_auto', 'months_since_last_claim',
       'months_since_policy_inception', 'number_of_open_complaints',
       'number_of_policies', 'total_claim_amount', 'month'],
      dtype='object')

### ➡️ Assigning X and Y

In [28]:
X = df[['coverage', 'education', 'location_code', 'policy', 'renew_offer_type',
       'sales_channel', 'vehicle_class', 'vehicle_size',
       'state_Arizona', 'state_California', 'state_Nevada', 'state_Oregon',
       'state_Washington', 'response_No', 'response_Yes',
       'employmentstatus_Disabled', 'employmentstatus_Employed',
       'employmentstatus_Medical Leave', 'employmentstatus_Retired',
       'employmentstatus_Unemployed', 'marital_status_Divorced',
       'marital_status_Married', 'marital_status_Single', 'gender_F',
       'gender_M', 'policy_type_Corporate Auto', 'policy_type_Personal Auto',
       'policy_type_Special Auto', 'customer_lifetime_value', 'income',
       'monthly_premium_auto', 'months_since_last_claim',
       'months_since_policy_inception', 'number_of_open_complaints',
       'number_of_policies', 'month']]

y = df['total_claim_amount']

### ➡️ Splitting

In [29]:
from sklearn.model_selection import train_test_split

In [30]:
X_train, X_test, y_train, y_test = train_test_split(X,y, random_state = 42)

### ➡️ Scale Transforming

In [31]:
from sklearn.preprocessing import PowerTransformer

In [32]:
pt = PowerTransformer()

In [33]:
pt.fit(X_train)

X_train_scaler = pt.transform(X_train)
X_test_scaler = pt.transform(X_test)